name: core_mixins
description: Collection of mixins implementing some dart libraries' abstract classes so you don't have to implement them.
version: 1.0.1+dev.1
homepage: https://github.com/LacticWhale/core_mixins

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
